"""Build and verify the standalone Move 3.27.3 Vellum canary APK."""

from __future__ import annotations

import argparse
import hashlib
import io
import os
import sys
import tarfile
import tempfile
import zlib
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from _tap_page_turn import _gzip_member, _tar_member


PACKAGE_NAME = "rmtool-fast-mono-reading-canary"
PACKAGE_VERSION = "3.27.3.0-r1"
DEPENDENCIES = (
    "qt-resource-rebuilder>=19.0.0",
    "qt-resource-rebuilder<20.0.0",
    "appload>=0.5.3",
    "remarkable-os=3.27.3.0-r0",
    "rmppmove=1.0.0-r0",
)
EXPECTED_QMD_SHA256 = "0fa777c1278318d1f98d18e7bbdbbb5dfadbd5baf463e4d7a8df0107c36a0f9d"
OUTPUT = REPO_ROOT / "build" / "refresh-optimization" / f"{PACKAGE_NAME}-{PACKAGE_VERSION}.apk"
QMD_PATH = f"home/root/xovi/exthome/qt-resource-rebuilder/{PACKAGE_NAME}.qmd"
LICENSE_DIR = f"home/root/.vellum/licenses/{PACKAGE_NAME}"
SOURCES = (
    "repository = https://github.com/pretenderlu/rmtool\n"
    "source = fast-mono-reading/qmd-src/fast-mono-reading-3.27.qmd\n"
    "firmware = 3.27.3.0 (20260612085811)\n"
).encode("ascii")


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def build_apk(qmd: bytes) -> bytes:
    license_text = (REPO_ROOT / "LICENSE").read_bytes()
    data_files = {
        QMD_PATH: (qmd, 0o644),
        f"{LICENSE_DIR}/LICENSE": (license_text, 0o644),
        f"{LICENSE_DIR}/SOURCES": (SOURCES, 0o644),
    }
    data_member = _gzip_member(_tar_member(data_files))
    pkginfo = "\n".join(
        (
            "# Generated by rmtool",
            f"pkgname = {PACKAGE_NAME}",
            f"pkgver = {PACKAGE_VERSION}",
            "pkgdesc = Fast monochrome reading canary for Move 3.27.3.0",
            "url = https://github.com/pretenderlu/rmtool",
            "builddate = 0",
            "packager = rmtool",
            f"size = {sum(len(data) for data, _mode in data_files.values())}",
            "arch = noarch",
            f"origin = {PACKAGE_NAME}",
            "license = GPL-3.0-only",
            *(f"depend = {dependency}" for dependency in DEPENDENCIES),
            f"datahash = {sha256(data_member)}",
            "",
        )
    ).encode("utf-8")
    control_member = _gzip_member(
        _tar_member({".PKGINFO": (pkginfo, 0o644)}, apk_checksums=False, end_archive=False)
    )
    return control_member + data_member


def tar_files(data: bytes) -> dict[str, bytes]:
    files: dict[str, bytes] = {}
    with tarfile.open(fileobj=io.BytesIO(data), mode="r:") as archive:
        for member in archive.getmembers():
            if not member.isfile():
                continue
            source = archive.extractfile(member)
            if source is None or member.name in files:
                raise RuntimeError("APK contains an unreadable or duplicate file")
            files[member.name] = source.read()
    return files


def apk_members(apk: bytes) -> tuple[dict[str, bytes], dict[str, bytes]]:
    control_stream = zlib.decompressobj(16 + zlib.MAX_WBITS)
    control = control_stream.decompress(apk) + control_stream.flush()
    if not control_stream.unused_data:
        raise RuntimeError("APK data member is missing")
    data_stream = zlib.decompressobj(16 + zlib.MAX_WBITS)
    data = data_stream.decompress(control_stream.unused_data) + data_stream.flush()
    if data_stream.unused_data:
        raise RuntimeError("APK contains an unexpected trailing member")
    return tar_files(control), tar_files(data)


def verify_apk(apk: bytes, qmd: bytes) -> None:
    control, data = apk_members(apk)
    if set(control) != {".PKGINFO"}:
        raise RuntimeError("APK control member contains unexpected files")
    expected_paths = {QMD_PATH, f"{LICENSE_DIR}/LICENSE", f"{LICENSE_DIR}/SOURCES"}
    if set(data) != expected_paths or data[QMD_PATH] != qmd:
        raise RuntimeError("APK data member does not match the canary file whitelist")
    if data[f"{LICENSE_DIR}/LICENSE"] != (REPO_ROOT / "LICENSE").read_bytes():
        raise RuntimeError("APK license metadata is invalid")
    if data[f"{LICENSE_DIR}/SOURCES"] != SOURCES:
        raise RuntimeError("APK source metadata is invalid")
    pkginfo = control[".PKGINFO"].decode("utf-8")
    lines = pkginfo.splitlines()
    if f"pkgname = {PACKAGE_NAME}" not in lines or f"pkgver = {PACKAGE_VERSION}" not in lines:
        raise RuntimeError("APK package identity is invalid")
    actual_dependencies = tuple(
        line.removeprefix("depend = ") for line in lines if line.startswith("depend = ")
    )
    if actual_dependencies != DEPENDENCIES:
        raise RuntimeError("APK dependencies are invalid")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--compiled-qmd", type=Path, required=True)
    args = parser.parse_args()
    qmd = args.compiled_qmd.read_bytes()
    if sha256(qmd) != EXPECTED_QMD_SHA256:
        raise RuntimeError("Compiled QMD does not match the validated Move 3.27.3 canary")

    apk = build_apk(qmd)
    if apk != build_apk(qmd):
        raise RuntimeError("APK build is not deterministic")
    verify_apk(apk, qmd)

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(dir=OUTPUT.parent, delete=False) as temporary:
        temporary.write(apk)
        temporary.flush()
        os.fsync(temporary.fileno())
        temporary_path = Path(temporary.name)
    os.replace(temporary_path, OUTPUT)
    print(f"package={PACKAGE_NAME}")
    print(f"version={PACKAGE_VERSION}")
    print(f"dependencies={','.join(DEPENDENCIES)}")
    print(f"installed_qmd=/{QMD_PATH}")
    print(f"apk_sha256={sha256(apk)}")
    print(f"output={OUTPUT}")
    print("verification=PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
