// XOVI project import / resource header file. This file is autogenerated. Do not edit.
#ifndef _XOVIGEN
#define _XOVIGEN
#ifdef __cplusplus
extern "C" {
#endif
#ifndef XOVI_PUBLIC_API
#define XOVI_PUBLIC_API
#define XOVI_VERSION "0.2.0"
#include <stdbool.h>

#define LP1_F_TYPE_EXPORT 1
#define LP1_F_TYPE_IMPORT 2
#define LP1_F_TYPE_OVERRIDE 3
#define LP1_F_TYPE_CONDITION 4

#define METADATA_TYPE_INT 1
#define METADATA_TYPE_BOOL 2
#define METADATA_TYPE_STRING 3

typedef union {
    int i;
    bool b;
    struct {
        int sLength;
        const char *s;
    };
} XoviMetadataValue;

struct XoviMetadataEntry {
    const char *name;
    char type;
    XoviMetadataValue value;
};

// Public version of the metadata iterator.
struct ExtensionMetadataIterator {
    const char *extensionName;
    const char *functionName;
    void *functionAddress;
    char OPAQUE[sizeof(void *) * 4 + sizeof(bool)];
};

struct XoViEnvironment {
    char *(*getExtensionDirectory)(const char *family);
    void (*requireExtension)(const char *name, unsigned char major, unsigned char minor, unsigned char patch);

    // 0.2.0 API - metadata:
    int (*getExtensionCount)();
    int (*getExtensionNames)(const char **table, int maxCount);
    int (*getExtensionFunctionCount)(const char *key);
    int (*getExtensionFunctionNames)(const char *extension, const char **table, int maxCount);

    int (*getMetadataEntriesCountForFunction)(const char *extension, const char *function, int functionType);
    struct XoviMetadataEntry **(*getMetadataChainForFunction)(const char *extension, const char *function, int functionType);
    struct XoviMetadataEntry *(*getMetadataEntryForFunction)(const char *extension, const char *function, int functionType, const char *metadataEntryName);

    void (*createMetadataSearchingIterator)(struct ExtensionMetadataIterator *iterator, const char *metadataEntryName);
    struct XoviMetadataEntry *(*nextFunctionMetadataEntry)(struct ExtensionMetadataIterator *iterator);
};
#endif


extern const void *LINKTABLEVALUES[];

// Imports
#define $_ZN11QTranslator4loadERK7QLocaleRK7QStringS5_S5_S5_ ((bool (*)(vptr, cvptr, cvptr, cvptr, cvptr, cvptr)) LINKTABLEVALUES[5])
#define $_ZN11QTranslator4loadERK7QStringS2_S2_S2_ ((bool (*)(vptr, cvptr, cvptr, cvptr, cvptr)) LINKTABLEVALUES[6])
#define $_ZN7QStringC1EPK5QCharx ((void (*)(vptr, cvptr, i64)) LINKTABLEVALUES[7])
#define $_ZNK7QLocale8languageEv ((int (*)(cvptr)) LINKTABLEVALUES[8])

// Resources


// Environment
extern const struct XoViEnvironment *Environment;

#ifdef __cplusplus
}
#endif
#endif
